import type { CollectionSection } from "@/types/vault";

export const VAULT_COLLECTIONS: CollectionSection[] = [
  {
    key: "accessories",
    label: "ACCESSORIES",
    itemCount: 24,
    description: "Veils, tiaras, jewelry, bags",
    position: [0, 3.18, 0],
    size: [3.8, 0.95, 0.3],
    route: "/collections/accessories",
    accent: "#ece8dd",
  },
  {
    key: "bridal",
    label: "BRIDAL",
    itemCount: 24,
    description: "Gold rail silhouettes",
    position: [-2.35, -0.18, 0],
    size: [2.0, 3.2, 0.3],
    route: "/collections/bridal",
    accent: "#c9a84c",
  },
  {
    key: "quinceanera",
    label: "QUINCEAÑERA",
    itemCount: 24,
    description: "Ballgown silhouettes",
    position: [0, -0.18, 0],
    size: [2.2, 3.55, 0.3],
    route: "/collections/quinceanera",
    accent: "#e3c05f",
  },
  {
    key: "prom-formal",
    label: "PROM & FORMAL",
    itemCount: 24,
    description: "Sleek evening silhouettes",
    position: [2.35, -0.18, 0],
    size: [2.0, 3.1, 0.3],
    route: "/collections/prom-formal",
    accent: "#c89f40",
  },
  {
    key: "shoes-bags",
    label: "SHOES & BAGS",
    itemCount: 24,
    description: "Boxes and display shelves",
    position: [0, -2.85, 0],
    size: [4.0, 1.05, 0.3],
    route: "/collections/shoes-bags",
    accent: "#d0b35f",
  },
];
