import type { CollectionSection } from "@/types/vault";

export const VAULT_COLLECTIONS: CollectionSection[] = [
  {
    key: "accessories",
    label: "THE CROWN COLLECTION",
    itemCount: 24,
    description: "Tiaras, veils, jewelry, hair pieces",
    position: [0, 3.05, 0],
    size: [3.85, 0.9, 0.3],
    route: "/collections/accessories",
  },
  {
    key: "bridal",
    label: "BRIDAL",
    itemCount: 24,
    description: "White & ivory gowns",
    position: [-2.35, -0.18, 0],
    size: [2.0, 3.25, 0.3],
    route: "/collections/bridal",
  },
  {
    key: "quinceanera",
    label: "QUINCEAÑERA",
    itemCount: 24,
    description: "Big colorful ballgowns",
    position: [0, -0.18, 0],
    size: [2.25, 3.6, 0.3],
    route: "/collections/quinceanera",
  },
  {
    key: "prom-formal",
    label: "PROM & FORMAL",
    itemCount: 24,
    description: "Sleek elegant gowns",
    position: [2.35, -0.18, 0],
    size: [2.0, 3.15, 0.3],
    route: "/collections/prom-formal",
  },
  {
    key: "evening",
    label: "EVENING",
    itemCount: 24,
    description: "Cocktail and black-tie gowns",
    position: [4.45, -0.18, 0],
    size: [2.0, 3.15, 0.3],
    route: "/collections/evening",
  },
  {
    key: "shoes-bags",
    label: "THE GLASS SLIPPER COLLECTION",
    itemCount: 24,
    description: "Shoes, bags, accessories",
    position: [0, -2.88, 0],
    size: [3.95, 1.0, 0.3],
    route: "/collections/shoes-bags",
  },
];
